openapi: "3.0.0"
info:
  title: Momji api
  description: >-
    Ce document présente la specification OpenApi 3 (contrat de l'api) pour le
    backend  du projet Momji.<br>
    Swagger : [http://swagger.io](http://swagger.io).<br>
  termsOfService: 'http://api.momji-api.com/terms'
  contact:
    name: API Support
    url: http://www.momjiapi.com/support
    email: apiteam@momji.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger/OpenApi
  url: 'http://swagger.io'
servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      environment:
        default: 'localhost'
        enum:
          - 'localhost'
      protocol:
        default: http
        enum:
          - 'http'
      port:
        default: '3000'
        enum:
          - '3000'
        
tags:
  - name: Teams
    description: Operations sur la ressource Team
  - name: Employees
    description: Operations sur la ressource Employee

paths:
  /teams:
    get:
      tags:
        - Teams
      responses:
        '200':
          description: Successfully getting teams
          content:
            application/json:
              schema:
                type: array
                example:
                  - id: 4 
                    name: team1
                    description: team1,
                    updated_at: "2021-08-11T20:59:44.000Z"
                    created_at: "2021-08-13T15:25:55.960Z"
                  - id: 4 
                    name: team1
                    description: team1,
                    updated_at: "2021-08-11T20:59:44.000Z"
                    created_at: "2021-08-13T15:25:55.960Z"
                  - id: 4 
                    name: team1
                    description: team1,
                    updated_at: "2021-08-11T20:59:44.000Z"
                    created_at: "2021-08-13T15:25:55.960Z"
                required:
                  - id  
                  - name
                  - description  
                  - status
                  - updated_at
                  - created_at

  /teams/{id}:
    get:
      tags:
        - Teams
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Team unique identifier
      responses:
        '200':
          description: Successfully getting team
          content:
            application/json:
              schema:
                example:
                  id: 4 
                  name: team1
                  description: team1,
                  updated_at: "2021-08-11T20:59:44.000Z"
                  created_at: "2021-08-13T15:25:55.960Z"
                required:
                  - id  
                  - name
                  - description  
                  - status
                  - updated_at
                  - created_at
        '404':
          description: Team not found
          content:
            application/json:
              schema:
                example: team not found
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                example: id must be a number
    